# flexget example config.yml
# please be kind to raspberrypi.org if you adjust for testing
---
schedules:
  - tasks: [raspberrypios]
    interval:
      days: 14
      jitter: 60

tasks:
  raspberrypios:
    rss:
      url: "https://downloads.raspberrypi.org/rss.xml"
    regexp:
      accept:
        - '2024-03-15'
    download: "/watch_folder"
